# \u5F00\u53D1\u73AF\u5883
server:
  port: 8989
spring:
  datasource:
    # MySQL \u9A71\u52A8
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL \u94FE\u63A5\u5730\u5740
    url: jdbc:mysql://192.168.216.131:3306/spring-teach?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    # MySQL \u7528\u6237\u540D
    username: root
    # MySQL \u5BC6\u7801
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
  type-aliases-package: com.dawn.entity
  mapper-locations: classpath:/mapper/*Mapper.xml

# springdoc-openapi\u9879\u76EE\u914D\u7F6E
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.controller
# knife4j\u7684\u589E\u5F3A\u914D\u7F6E\uFF0C\u4E0D\u9700\u8981\u589E\u5F3A\u53EF\u4EE5\u4E0D\u914D
knife4j:
  enable: true
  setting:
    language: zh_cn